# Spring Application Name
spring.application.name=bib-flip-backend

# Default Spring Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:azure}

# Mail Server Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bibflip@123.com
spring.mail.password=1234
spring.mail.from=bibflip@123.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# JWT Configuration
authorization.jwt.secret=H7h1N5nDyb+JgV6vTxMJ0hO7LuZBeL9kFq5eVjz8kzM=
authorization.jwt.expiration.days=7

# Time Zone Configuration (Will be descommented in future sprint to use America/Lima timezone)
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima
spring.jackson.time-zone=America/Lima